name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ ae8fd580-6e9f-47a9-9427-826d54ac6b1b}}
        run: |
          lhci autorun \
            --collect.url=https://urbangents2.yeetonline.com/ \
            --upload.target=lhci \
            --upload.serverBaseUrl=http://localhost:9001 \
            --upload.token=$LHCI_GITHUB_APP_TOKEN
